### ISSUE TITLE
Extend for individual read and write meshes

### ISSUE THREAD

**Issue by uekerman** [BenjaminRueth/waveform-bindings#1]
Currently, the waveform bindings assume that reading and writing data happens on the same mesh. 
https://github.com/BenjaminRueth/waveform-bindings/blob/42766641b1e6cae327ca293be6241025e6b0c695/waveformbindings/waveformbindings.py#L37

This assumption is not valid for Nutils. We have e.g.:
```xml
  <data:vector name="Forces1"/>
  <data:vector name="Displacements1"/>

  <mesh name="SOLIDZ_Mesh">
     <use-data name="Displacements1"/>
     <use-data name="Forces1"/>
  </mesh>

  <mesh name="Nutils-Mesh-GP">
    <use-data name="Displacements1" />
  </mesh>
  
  <mesh name="Nutils-Mesh-CC">
    <use-data name="Forces1"/>
  </mesh>
  
...

  <participant name="Nutils">
    <use-mesh name="SOLIDZ_Mesh" from="SOLIDZ"/>
    <use-mesh name="Nutils-Mesh-GP" provide="yes"/>
    <use-mesh name="Nutils-Mesh-CC" provide="yes"/>
    <mapping:rbf-thin-plate-splines direction="read"  from="SOLIDZ_Mesh" to="Nutils-Mesh-GP" constraint="consistent"/>
    <mapping:rbf-thin-plate-splines direction="write"  from="Nutils-Mesh-CC" to="SOLIDZ_Mesh" constraint="conservative"/>
    <read-data name="Displacements1" mesh="Nutils-Mesh-GP" />
    <write-data name="Forces1" mesh="Nutils-Mesh-CC" />
  </participant>    
```

**Comment by BenjaminRodenberg** [comment]
I currently have two ideas, how we could handle this issue:

1. If we change the signature of `initialize_waveforms`, this will break backwards compatibility. Then we could do something like `initialize_waveforms(self, write_info, read_info)`, where `write/read_info` provides all the information that is needed via a dictionary. For example: `write_info = {'mesh_id': 1, 'n_vertices': 3, 'vertex_ids': [0,1,2], 'data_name': 'dummy', 'dimension': 2}. This might even be extended to lists of dictionaries in the future, if we have multiple datasets.

2. If we do not want to change the signature of `initialize_waveforms` and keep everything backwards compatible, we could apply the "dictionary-idea" only to the mesh related quantities: `mesh_id = 1` becomes `mesh_id = {'read': 1, 'write': 0}. The same approach is used for `n_vertices` and `vertex_ids`. Inside `initialize_waveforms` we can check whether `mesh_id` etc. is a dictionary (with keys `read` and `write`) or not. If the user does not provide dictionaries (i.e. only a single mesh), nothing changes. If the user provides dictionaries, different meshes might be used for write and read data. This looks to me more messy, but does not break backwards compatibility.

@uekerman Which of the two approaches do you prefer?

**Comment by uekerman** [comment]
I don't consider backwards compatibility an issue here as nobody except us uses the waveform bindings so far. So, option 1.

**Comment by BenjaminRodenberg** [comment]
@uekerman Can we close this issue?

**Comment by uekerman** [comment]
yes
